server {
  listen 80;
  server_name _;
  client_max_body_size 55m;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://api:9111;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
  }
  location / { try_files $uri $uri/ /index.html; }
}
